version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: yape-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yape_transporte
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: yape-backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/yape_transporte?schema=public"
      JWT_SECRET: "ClaveSeguraParaProduccion_2025"
      PORT: 3000
      NODE_ENV: production
    depends_on:
      - db

volumes:
  postgres_data:
